### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by NicoCG** [RankoHata/P2P_Chat#1]
Thanks for building this! I just have a few questions.

Will I be able to run this on a server somewhere example codeanywhere.com and I will be able to talk to that client using that assigned domain example chat.bob.com:443 or does this need to be run locally for it to work?

**Comment by RankoHata** [comment]
- The server needs to run server.py.
- The client needs to run client.py.

The premise of the normal operation of the program is that each peer can use the TCP socket to connect to each other through IP and port.

Please note that this program can only run correctly if each peer has a static IP and port.

**Comment by RankoHata** [comment]
> Thanks for building this! I just have a few questions.
> 
> Will I be able to run this on a server somewhere example codeanywhere.com and I will be able to talk to that client using that assigned domain example chat.bob.com:443 or does this need to be run locally for it to work?

- The server needs to run server.py.
- The client needs to run client.py.

The premise of the normal operation of the program is that each peer can use the TCP socket to connect to each other through IP and port.

Please note that this program can only run correctly if each peer has a static IP and port.

**Comment by NicoCG** [comment]
Thanks can the port be ssl? And can I use domain instead of ip?

**Comment by RankoHata** [comment]
> Thanks can the port be ssl? 

If you want to use SSL, you need to modify the code.
You may need this library.
[ssl](https://docs.python.org/3/library/ssl.html)

> And can I use domain instead of ip?

Sure.

**Comment by Srinivas142000** [comment]
Hey would you mind if i use your code for project purpose? i am trying to compare all the network architectures and your code will be helpful, so can i have your permission?
